"""Describe your e

Revision ID: 28b843833d59
Revises: d5e092d9f200
Create Date: 2025-12-08 19:00:31.109793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b843833d59'
down_revision = 'd5e092d9f200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('employment_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('employment_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('employment_end_date')
        batch_op.drop_column('employment_start_date')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
